- R.swift/func.swift
- R.swift/main.swift
After following the installation instructions I encountered build errors informing me that `UIImage` and `UIStoryboard` were unknown types. I've update the code generator to include an import of `UIKit` to resolve these errors.
Now, I would imagine this issue would have come up earlier if it's affecting everyone - so maybe I missed something that would have resolved this without code changes.
Also, I thought I should inform you that the idea behind this project is genius - I thought that I would always have to deal with storyboards/images as strings, I didn't know there was a better way until now, and I love the better way! Thank you!
> Add UIKit import to generated file

- R.swift/types.swift
Hi,
I like to put my images in sub-folders in an asset catalog, this ease the find and reading of assets when you have a lot of them.
R.swift was not listing these images, it was only listing the images at the root of an asset catalog. Here is a change to add these images in the image struct.
This change places all images in the same struct. As a future improvement, we could put them in a struct that represents the folder in which the image was.
> Handle asset catalog sub-folders

- R.swift/func.swift
- R.swift/main.swift
- R.swift/types.swift
- R.swift/values.swift
Attempt to implement issue #21
Current concerns:
(I want it to be simple to start using R.swift and not force users to use our higher level functions as this could mean being not able to use R values in certain edge cases.)
> Better reuse identifiers

- R.swift/func.swift
- R.swift/main.swift
- R.swift/types.swift
- R.swift/values.swift
- README.md
From https://github.com/mac-cain13/R.swift/issues/38
Finally, no need to use options or weird path.
Does not yet support system fonts (needs quite some extra work to add available annotations to R.swift).
> Add support for custom fonts

- R.swift.podspec
I think this is all that's needed to add tvOS support to R.swift (https://github.com/mac-cain13/R.swift/issues/105).
I also looked into adding Mac OSX support (https://github.com/mac-cain13/R.swift/issues/102), but that's a bit more work.
R.swift is currently hardcoded to using UIKit, that would need to be made dynamic to also support AppKit.
> Support tvOS in podspec

- Documentation/QandA.md
- R.swift/func.swift
- README.md
`UIImage.init(named:inBundle:compatibleWithTraitCollection:)` is only available in iOS 8.0 and later.
By using swifts new `#available(iOS 8.0, *)` check and `UIImage(named:<name>)` as fallback, R.swift can also be used for on iOS7. 
There's one caveat though: `UIImage(named:<name>)` can only load images from the main bundle. I think that this is OK (and it's documented in the Q&A) because this is mostly relevant when using dynamic frameworks (e.g. in 3rd party swift dependencies) which is not supported on iOS7 anyway.
> Use availability check and iOS7 fallback for UIImage

- R.swift/types.swift
This is a minor patch to let R.swift list fonts that have uppercase file name and extensions (e.g. `.TFF` instead of `.ttd`).
> Support for font with uppercase file extensions

- Documentation/Examples.md
- R.swift/Generators/ResourceFileGenerator.swift
Resolves 'ambiguous use of file' described in https://github.com/mac-cain13/R.swift/issues/150
Since most uses of `R.file.someFile()` seems to be NSURL, the other overload of String was removed.
The path String is still available via `R.file.someFile.path()`.
> Remove R.file.someFile() returning String?

- R.swift/Generators/ImageGenerator.swift
- R.swift/Generators/NibGenerator.swift
- R.swift/Generators/ResourceFileGenerator.swift
- R.swift/Generators/ReuseIdentifierGenerator.swift
- R.swift/Generators/SegueGenerator.swift
- R.swift/Generators/StoryboardGenerator.swift
- R.swift/Util/SanitizedSwiftName.swift
- R.swift/Util/UtilExtensions.swift
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
- ResourceApp/ResourceApp/WhitespaceReuseIdentifer.xib
Implements https://github.com/mac-cain13/R.swift/issues/137
No longer generate (invalid) code for sanitized Swift identifiers that are an empty string. Instead print a warning. 
The code for printing warnings is a bit repetitive, and can be cleaned up. This falls under https://github.com/mac-cain13/R.swift/issues/136, I think.
> Don't generate code for empty identifier

- Podfile.lock
- R.swift.xcworkspace/contents.xcworkspacedata
- R.swift/ResourceTypes/Nib.swift
- R.swift/input.swift
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
Issues fixed:
- The workspace reference to the R.swift.Library project was an absolute path instead of a relative path.
- The ResourceAppTests target still had leftover Framework search paths from Xcode 6
- Swift 2.2 deprecated ++/-- operators
- Swift 2.2 deprecated function currying syntax
Let me know if you want me to bump the podspec version.
> Fix warnings in Xcode 7.3

- R.swift/Util/SanitizedSwiftName.swift
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
- ResourceApp/ResourceApp/Files/#column
- ResourceApp/ResourceApp/Files/__FILE__
- ResourceApp/ResourceApp/Files/associatedtype
Adds some test files to `ResourceApp` with reserved keywords as file names.
Adds `associatedtype` as keyword in the code generator.
> Add Swift 2.2 reserved keywords

- R.swift.xcodeproj/project.pbxproj
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
Sets the indentation style used in R.swift in the project file. So contributors don't have to change their Xcode settings.
> Project wide indentation settings

- R.swift/Generators/StringsGenerator.swift
When using R.swift in a bundle that is not the main bundle, an explicit `bundle:` is needed for `NSLocalizedString`.
Requires: https://github.com/mac-cain13/R.swift.Library/pull/13
> Add hosting bundle to string resource, and NSLocalizedString

- Package.resolved
- Package.swift
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
- ResourceApp/ResourceAppTests/ResourceAppTests.swift
- Sources/RswiftCore/ResourceTypes/Xcodeproj.swift
Previously, rswift would crash on a xcodeproj file with broken references.
This was due to the XcodeEdit dependency that used a lot of implicitly unwrapped optionals.
With the update to XcodeEdit 2, rswift will not longer crash, but instead will log a warning and continue on. 
Example of the type of warning that is logged:
```
warning: [R.swift] project.pbxproj is internally inconsistent.
- PBXBuildFile (DEADBEEFDEADBEEFDEADBEEF) references missing fileRef C0FEFEC0FEFEC0FEFEC0FEFE
- PBXBuildFile (DEADBEEFDEADBEEFDEADBEEF) is not used
Perhaps a merge conflict?
```
> Don't crash on broken xcodeproj

- Sources/RswiftCore/Generators/AggregatedStructGenerator.swift
HI! I am trying to alter the generation of the structs so that the generated R file wouldn't include the empty ones. Strangely enough, when I reference this commit in the `Podfile`, so that I would have this version instead of the `4.0.0` tag, after `pod install` I am not able to build anymore. The original project after my changes compiles just fine, it is only through Cocoapods - `rswift` file is simply not there.
Could you help me out please? Maybe I have missed something. Really struggling here. Thanks!
> Attempt to not include empty structs into the generated file.

- Documentation/QandA.md
- State you ideally need a dedicated xcode project to include build script
- Add link to issue explaining this
- Change example script with `accessLevel` for Cocoapod users: 
If you have a dedicated xcode project for your library and you use R.swift in your library you need to install it somehow right? Probably with a regular Podfile? and thus the script needs to be changed to `"$SRCROOT/Pods/R.swift/rswift" generate "$SRCROOT"`
> Docs - QA - improve: use in library

- ResourceApp.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
- ResourceApp/ResourceAppTests/ResourceAppTests.swift
- Sources/RswiftCore/Generators/NibStructGenerator.swift
- Sources/RswiftCore/Generators/StoryboardGenerator.swift
- Sources/RswiftCore/Util/SwiftIdentifier.swift
- Sources/RswiftCore/Util/UtilExtensions.swift
I noticed on the latest alpha, `R.generated.swift` was slightly different every time. As part of my build, I actually run a local diff on the newly generated `R.generated.swift` and the existing one, and only use the new one if something has changed. Otherwise, Xcode would always see that a file had been touched, and the incremental builds would not be as efficient as they could be.
This PR just sorts things that were mapped to a non-ordered data type at some point.
I might have missed some, but this was at least giving my project consistent results.
> Sort results so output is consistent every run.

- Sources/RswiftCore/ResourceTypes/Resources.swift
- Sources/RswiftCore/Util/Glob.swift
- Tests/RswiftCoreTests/GlobTests.swift
This PR brings 2 performance enhancements.
When ignoring files using `.rswiftignore`, all potential ignored files are calculated during the creation of `IgnoreFile`. It iterates recursively through all subdirectories in `.rswiftignore`'s root directory. The problem here is that will often include `Pods`, and depending on the project could include `node_modules` as well. These directories can of course be massively complex compared to the actual user project.
Instead of iterating recursively through all subdirectories from root, the new solution is to do a shallow iteration through the root directory, ignore `Pods` and `node_modules`, and then iterate recursively through the rest.
Large projects can have a significant amount of resources. In `Resources.init`, all the resources were being …
> Performance Tweaks

- Sources/RswiftCore/ResourceTypes/Resources.swift
Under the 4.x line `R.generated.swift` would contain both an entry in both `image` and `file` for *stand alone* image files. This was very useful as many of Apple's API's require an image `URL` or path rather than just a `UIImage` object.
e.g.
```swift
/// This `R.file` struct is generated, and contains static references to 18 files.
struct file {
/// Resource file `notification-alert1.png`.
static let notificationAlert1Png = Rswift.FileResource(bundle: R.hostingBundle, name: "notification-alert1", pathExtension: "png")
/// Resource file `notification-alert2.png`.
static let notificationAlert2Png = Rswift.FileResource(bundle: R.hostingBundle, name: "notification-alert2", pathExtension: "png")
…and so on…
```
So usage in places like this are common place: 
```swift …
```
> Fix for stand alone images not being listed as file resources.

- .gitignore
- Package.swift
- README.md
This PR includes the previous pull request from @lilpit and adds the following modifications:
- provides the additional documentation requested by @mac-cain13 in the original PR review
- adds .swiftpm to the .gitignore file (pretty sure this should be ignored)
As a refresher, @lilpit submitted #485 :
> If you don't use Cocoapods in your project, there is no proper way to manage the R.swift dependancy.
> 
> A dependency manager based on SwifPM called Mint is ganning traction in the community and is already supported by some other swift based tools like Carthage or SwiftGen.
> 
> This PR just adds a product to Package.swift, the only required thing needed by Mint to work.
> To make R.swift installable via mint, a new Release of R.Swift will be needed
**NOTE**: My `R.Swift.Library` [Pull …
> Add Mint Support (Includes Updated Documentation)

- Sources/RswiftCore/CallInformation.swift
- Sources/RswiftCore/SwiftTypes/CodeGenerators/ImportPrinter.swift
- Sources/rswift/main.swift
I updated `ImportPrinter` to change the order of the imports that are
generated in the output source code. Previously all imports were being
sorted alphabetically and then output to the generated source code. This
was a problem if `R.swift.library` is being statically linked in another
dynamic framework and the containing framework's module name is
alphabetically after the `Rswift` module name. In this case, the Swift
compiler does not correctly import the `Rswift` module.
I changed `ImportPrinter` to always output modules that are specified
using the `--import` command line argument before modules that are
extracted from the source code. This should fix the import issue.
I updated `CallInformation.swift` to pass the list of modules as an array
instead of a set in order to keep the order …
> Reorder Module Imports in Generated Source Code

- Sources/RswiftCore/ResourceTypes/Resources.swift
Fixes: https://github.com/mac-cain13/R.swift/issues/498
In R.swift 4, standalone images would exist under R.image and R.file and fonts under R.font and R.file.
R.swift 5.0 changed this (accidentally) so images would only be under R.image. This was previously fixed. This PR also fixes it for fonts (and other assets).
This only adds different types to R.file (if applicable), because it was the only type I could think of that includes assets that also appear somewhere else.
If there's more types that include multiple assets, we should fix this more generally (by replacing all `else if let` with `if let`)
> Restore fonts in R.file

- Sources/RswiftCore/SwiftTypes/Module.swift
Fixes https://github.com/mac-cain13/R.swift/issues/548
> Interpret whitespace-only module name as empty

- Sources/RswiftCore/Generators/AggregatedStructGenerator.swift
- Sources/RswiftCore/Generators/StringsStructGenerator.swift
- Sources/RswiftCore/ResourceTypes/Locale.swift
- Sources/RswiftCore/ResourceTypes/Xcodeproj.swift
- Sources/RswiftCore/RswiftCore.swift
When generating comments for R.string, use developmentRegion from the Xcode project as fallback when no Base region is set.
Add warning about extra translation in non-base/development languages.
Fixes: https://github.com/mac-cain13/R.swift/issues/539
> Add developmentRegion after Base as default language

- ResourceApp/ResourceApp.xcodeproj/project.pbxproj
- ResourceApp/ResourceApp/References.storyboard
- ResourceApp/ResourceApp/SegueIdentifiers.storyboard
- ResourceApp/ResourceAppTests/ResourceAppTests.swift
- Sources/RswiftCore/Generators/SegueGenerator.swift
This PR causes the generator to skip any segues with an empty string identifier.
For some types of segues, such as from a UIButton to another view controller, a segue identifier is not required. When it **is** required, for example in a view controller initiated segue, Xcode will warn the user about it already, so R.swift doesn't need to warn about either case.
I'm not sure if I fixed it in the correct place, please let me know if you know a better way. :)
Closes #525
> SegueGenerator: Skip segues that have an empty identifier

- ResourceApp/ResourceAppTests/StringsTests.swift
I'm not sure why this changed in iOS 13. Nor can I find documentation about this change.
> Make exception in precision test for iOS 13

- Documentation/Examples.md
Fix a typo in the storyboard example to avoid confusion for the readers.
> Fix a typo in the storyboard example

- Sources/RswiftCore/RswiftCore.swift
This is a small change that make sure info plists and entitlement files are only parsed if the generators for those types are actually enabled. This is a workaround for an issue where URLs to entitlement files cannot be resolved at the moment.
Merging this PR would give users of the library the option to disable the entitlements generator if they don't need it and that way remove the warning  "[R.swift] File could not be parsed as InfoPlist from URL:  {entitlements url}"
> Only parse info and entitlements when generators are enabled

- Sources/RswiftCore/Generators/StringsStructGenerator.swift
When having a parameterised string with inner quotes in the key:
```swift
"Parameterised string with \"inner quotes\"" = "Parameterised %@ string with \"inner quotes\"";
```
`StringStructGenerator.stringFunctionParams(for:at:)` generates an unescaped string in the second `guard` statement:
```swift
static func parameterisedStringWithInnerQuotes(_ value1: String, preferredLanguages: [String]? = nil) -> String {
guard let preferredLanguages = preferredLanguages else {
let format = NSLocalizedString("Parameterised string with \"inner quotes\"", bundle: hostingBundle, comment: "")
return String(format: format, locale: applicationLocale, value1)
}
guard let (locale, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
return "Parameterised string with …
```
> Escape parameterised strings with inner quotes.

- Sources/RswiftCore/Generators/ColorStructGenerator.swift
I've run into the same issue as #559 where we're unable to use `R.colors.primary()` in our swift projects, as the function is not available for WatchOS targets.
I've modified the color generators to output colors for WatchOS as follows:
```
#if os(watchOS)
/// `UIColor(named: "primary", bundle: ..., traitCollection: ...)`
@available(watchOSApplicationExtension 4.0, *)
static func primary(compatibleWith traitCollection: Any? = nil) -> UIKit.UIColor? {
return UIKit.UIColor(named: R.color.primary.name)
}
#endif
```
I'm using `traitCollection: Any?` parameter as I need to pass a parameter, otherwise Xcode will take the function to be a redefinition of the resource, in this case `R.colors.primary`. I had to pass in Any, as UITraitCollection is not available in watchOS.
I also extracted the …
> Added color support for WatchOS

- Sources/RswiftCore/ResourceTypes/NameCatalog.swift
Addresses #678 
Named resources from the asset catalog (such as images or colors) were not properly being sorted in a stable way and re-generated `R.generated.swift` would have alternating sortings for some subset of assets.
In a recent custom comparison added to the new `NameCatalog`, `lhs` was referenced twice instead of compared properly against `rhs`. This PR fixes that and compares `lhs.name` to `rhs.name`.
> Fix for Named Asset Sort Issues

- Sources/RswiftCore/ResourceTypes/AssetFolder.swift
This patch adds support for custom symbol images [Apple Documentation - Creating Custom Symbol Images for Your App](https://developer.apple.com/documentation/uikit/uiimage/creating_custom_symbol_images_for_your_app)
Closes issue #685
> Support custom symbol image sets

- .github/workflows/checks.yml
- .github/workflows/release.yml
Fixes https://github.com/mac-cain13/R.swift/issues/691
Builds a fat binary for x86_64 and arm64
> Native M1 build with Fat binaries

- Sources/RswiftResources/Integrations/DataResource+Integrations.swift
Addresses #454 
There is only a simple initializer of `NSDataAsset` currently.
```swift
if let asset = NSDataAsset(resource: R.data.animation) {
let data = asset.data
}
```
This PR makes it possible to call like `let data = R.data.animation()`
> Add function to get `Data` from `DataResource` directly

- Documentation/Migration.md
Remove R.generated.swift on Xcode.
Because the following error.
Filename "R.generated.swift" used twice
> Update Migration Guide

- Sources/RswiftParsers/Resources/AssetCatalog+Parser.swift
This fixes a base path mismatch when assets URLs are located in `/private/tmp`.
See https://stackoverflow.com/questions/43031045/for-what-paths-is-resolvingsymlinksinpath-wrong
> Compare URLs with resolved symlinks

- Sources/rswift/App.swift
R.swift cannot find .rswiftignore for a project that isn't made by xcodeproj but Package.swift.
It is because that `SOURCE_ROOT` environment variable doesn't exist when a project is build with Package.swift and currently the source code references `./SOURCE_ROOT` literally.
issue: #819
> Fix sourceRootURL

- Sources/RswiftResources/Integrations/StringResource+Integrations.swift
As described in issue #812, when localizing strings containing arguments like "My number: %d", Rswift does not use the locale of the current environment when the locale argument is missing (which is the default behavior). So the string cannot be formatted correctly.
For example, in `Localizable.strings` in Japanese, when using %d, a comma should be inserted every three digits:
```
"My number: %d" = "数値：%d";
```
Current Rswift gives us this:
```swift
R.string.localizable.myNumberD(1234567890)
// 数値：1234567890
R.string(locale: Locale(identifier: "ja")).localizable.myNumberD(1234567890)
// 数値：1,234,567,890
```
After PR:
```swift
R.string.localizable.myNumberD(1234567890)
// 数値：1,234,567,890
R.string(locale: Locale(identifier: "ja")).localizable.myNumberD(1234567890)
// 数値：1,234,567,890
``` …
> Use current locale when overrideLocale is missing

- .github/workflows/release.yml
PR adds ability to create custom Swift Package Plugins. The idea is described [here](https://github.com/SwiftGen/SwiftGen/blob/stable/Documentation/Articles/SwiftGen-Build-Tool-Package-Plugins.md).
Example of plugin implementation:
**Package.swift**
```swift
// swift-tools-version: 5.8
import PackageDescription
let package = Package(
name: "RswiftPlugin",
platforms: [
.macOS(.v13),
.iOS(.v14),
],
products: [
.library(name: "RswiftPluginDependencies", targets: [ "RswiftPluginDependencies" ]),
.plugin(name: "RswiftPlugin", targets: [ "RswiftPlugin" ])
],
dependencies: [
.package(url: "https://github.com/mac-cain13/R.swift.git", exact: "7.3.2")
],
targets: [
.target(
name: "RswiftPluginDependencies",
dependencies: [
.product(name: "RswiftLibrary", package: "R.swift")
]
),
.plugin(
name: …
```
> Steps to create and release artifactbundle.

- Sources/RswiftResources/Integrations/StoryboardReference+Integrations.swift
This method calls `UIStoryboard.instantiateViewController(identifier:creator:)` internally, which returns a non-optional view controller. Therefore, it is unnecessary to return optional value in the `StoryboardViewControllerIdentifier` method.
See also: https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller
> `StoryboardViewControllerIdentifier.callAsFunction(creator:)` should return non-optional value

- README.md
Xcode's SPM cant resolve packages without a protocol, since i copied the URL directly from here and it was just silently failing it took me 4 hours and a system update to MacOS Sequoia to catch it............
> Add `https` protocol to SPM Installation
