R.swift/func.swift, R.swift/main.swift, R.swift/util.swift, README.md
=> First implementation of Nib support

R.swift/func.swift, R.swift/main.swift, R.swift/types.swift
=> Support for reuseIdentifiers in R

README.md
For people looking for Swift 2 support.
=> Link to the develop branch in Readme

Documentation/Examples.md, Documentation/QandA.md, README.md
Just fixed small typos that I found while looking at the documentation. Great project btw!
=> fixed typos

R.swift.xcodeproj/project.pbxproj, R.swift.xcodeproj/xcshareddata/xcbaselines/D5C4227C1B711FDF004EA9B9.xcbaseline/14F5F524-DCA5-4BC2-96F0-91274CB940AF.plist, R.swift.xcodeproj/xcshareddata/xcbaselines/D5C4227C1B711FDF004EA9B9.xcbaseline/Info.plist, R.swift.xcodeproj/xcshareddata/xcschemes/rswift.xcscheme, R.swift/func.swift, R.swift/util.swift, R.swift/values.swift, R.swiftTests/MainTests.swift, ResourceApp/ResourceApp/FirstViewController.swift, ResourceApp/ResourceAppTests/FontsTests.swift
=> Better filtering of invalid characters

Documentation/Examples.md
Implements https://github.com/mac-cain13/R.swift/issues/111
=> Add collection view cell example

Documentation/Examples.md
Was going through examples, noticed this.
=> Fixes a small error in Examples

R.swift/Generators/SegueGenerator.swift, R.swift/ResourceTypes/Storyboard.swift, ResourceApp/ResourceApp.xcodeproj/project.pbxproj, ResourceApp/ResourceApp/Base.lproj/Secondary.storyboard, ResourceApp/ResourceApp/References.storyboard, ResourceApp/ResourceAppTests/ResourceAppTests.swift
We now also check if the segue is pointing to a storyboard segue and try to resolve it. We can't resolve segues pointing to storyboards in another bundle, so these won't work atm.
Fixes #120
=> Make segue typing work with Storyboard segues

R.swift/ResourceTypes/Nib.swift, R.swift/SwiftTypes/Type.swift, ResourceApp/ResourceApp.xcodeproj/project.pbxproj, ResourceApp/ResourceApp/SupplementaryElement.xib, ResourceApp/ResourceAppTests/NibTests.swift
Fixes https://github.com/mac-cain13/R.swift/issues/162
=> add the UICollectionReusableView to the set nog NIB types

Readme.md
as of https://github.com/mac-cain13/R.swift/issues/60, r.swift is available in the homebrew package manager.
=> Add homebrew documentation to readme

R.swift/Generators/FontGenerator.swift, R.swift/Generators/ImageGenerator.swift, R.swift/Generators/NibGenerator.swift, R.swift/Generators/ResourceFileGenerator.swift, R.swift/Generators/ResourceGenerator.swift, R.swift/Generators/ReuseIdentifierGenerator.swift, R.swift/Generators/SegueGenerator.swift, R.swift/Generators/StoryboardGenerator.swift, R.swift/SwiftTypes/Function.swift, R.swift/SwiftTypes/Let.swift, R.swift/SwiftTypes/Struct.swift
Implements https://github.com/mac-cain13/R.swift/issues/125
Generate comments for some of the generated code.
Not everything is done yet, this is a work in progress.
=> Generate comments

.gitmodules, ResourceApp/ResourceApp.xcodeproj/project.pbxproj, ResourceApp/ResourceApp/Relative To Project/RelativeToProject.xib, ResourceApp/ResourceAppTests/NibTests.swift
Fixes https://github.com/mac-cain13/R.swift/issues/191
=> Update to newest Xcode.swift

R.swift/Generators/ResourceGenerator.swift
=> Fix a typo in ResourceGenerator.swift

R.swift/ResourceTypes/Storyboard.swift, ResourceApp/ResourceApp.xcodeproj/project.pbxproj, ResourceApp/ResourceApp/Base.lproj/Main.storyboard, ResourceApp/ResourceApp/Xib with ViewController.xib, ResourceApp/ResourceAppTests/SegueTests.swift
Reimplmentation of https://github.com/mac-cain13/R.swift/pull/221 with tests.
Fixes https://github.com/mac-cain13/R.swift/issues/224 and https://github.com/mac-cain13/R.swift/issues/248
=> Collect all segues in scene, associate with ViewController

R.swift/Generators/ResourceFileGenerator.swift, ResourceApp/ResourceApp.xcodeproj/project.pbxproj, ResourceApp/ResourceApp/Localized/Base.lproj/hello.txt, ResourceApp/ResourceApp/Localized/es.lproj/hello.txt, ResourceApp/ResourceApp/Localized/nl.lproj/hello.txt
For resource files, multiple localizations are supported in `R.file.*`.
Future work:
- Localized images
- Localized storyboards
- Localized nibs
- Any others?
=> Localized resource files

R.swift/main.swift
Fixes https://github.com/mac-cain13/R.swift/issues/298
=> Generate newline at end of file

Sources/RswiftCore/Generators/ColorStructGenerator.swift, Sources/RswiftCore/Generators/SegueGenerator.swift, Sources/RswiftCore/Generators/StoryboardGenerator.swift, Sources/RswiftCore/Generators/StringsStructGenerator.swift, Sources/RswiftCore/ResourceTypes/AssetFolder.swift, Sources/RswiftCore/Util/UtilExtensions.swift, Sources/rswift/main.swift
This fixes errors and warnings for the Swift 4 snapshot (2017-05-24).
Code is still compatible with Swift 3, so can already be merged.
=> Swift 4 fixes

Package.resolved, Sources/RswiftCore/Generators/ColorPaletteStructGenerator.swift, Sources/RswiftCore/Generators/ColorStructGenerator.swift, Sources/RswiftCore/Generators/FontStructGenerator.swift, Sources/RswiftCore/Generators/ImageStructGenerator.swift, Sources/RswiftCore/Generators/NibStructGenerator.swift, Sources/RswiftCore/Generators/ResourceFileStructGenerator.swift, Sources/RswiftCore/Generators/SegueGenerator.swift, Sources/RswiftCore/Generators/StoryboardGenerator.swift, Sources/RswiftCore/Generators/StringsStructGenerator.swift, Sources/RswiftCore/Generators/ValidatedStructGenerator.swift, Sources/RswiftCore/ResourceTypes/StringParam.swift, Sources/RswiftCore/SwiftTypes/CodeGenerators/ImportPrinter.swift, Sources/RswiftCore/SwiftTypes/Function.swift, Sources/RswiftCore/Util/UtilExtensions.swift
As discussed in https://github.com/mac-cain13/R.swift/issues/204#issuecomment-326504069
=> Move @available annotations for R.color

Documentation/Examples.md
=> Update Color example to use .clr instead of .color

Package.resolved, Package.swift
Fixes https://github.com/mac-cain13/R.swift/issues/419
=> Update to XcodeEdit 2.3.0, support for PBXLegacyTarget

Documentation/QandA.md
=> Docs - QA - add forgotten generate

Sources/RswiftCore/ResourceTypes/Nib.swift, Tests/RswiftCoreTests/NibParserDelegateTests.swift
Adds a test case with the kind of problem encountered when running R.swift 5.0.0-alpha1 in Xcode 10 and a attempt to fix it.
=> Fixes parsing problem in NibParserDelegate.

Package.resolved
Resolves https://github.com/mac-cain13/R.swift/issues/536
=> Update XcodeEdit dependency

Sources/RswiftCore/Util/Struct+InternalProperties.swift
=> Explit reference to Locale.init, resolves #572

.github/workflows/checks.yml, .github/workflows/release.yml, R.swift.podspec, Sources/rswift/Rswift.swift, fastlane/Fastfile
and a few other improvements for testing using Github Actions.
=> Use Github actions for releases

Documentation/QandA.md
Fixed grammatical errors, improved wording
=> Update QandA doc

R.swift.podspec
update podspec R.swift.Library ~> 5.4.0
=> update podspec R.swift.Library ~> 5.4.0

Documentation/Migration.md, Examples/ResourceApp/ResourceApp/Strings/Generic.strings, Examples/ResourceApp/ResourceApp/Strings/en.lproj/Localizable.strings, Examples/ResourceApp/ResourceApp/Strings/es.lproj/Localizable.strings, Examples/ResourceApp/ResourceApp/Strings/ja.lproj/Localizable.strings, Examples/ResourceApp/ResourceAppTests/StringsTests.swift, Sources/RswiftResources/Integrations/StringResource+Integrations.swift
Fixes https://github.com/mac-cain13/R.swift/issues/711
=> Always use String(format:), also for strings without arguments

Sources/RswiftResources/Integrations/StoryboardReference+Integrations.swift
=> Support dependency injection with storyboards

Documentation/Examples.md
Fix the example testcase so that it works and is not confusing.
=> Fix example testcase in Examples.md

Examples/ResourceApp/ResourceAppTests/InfoPlistTests.swift, Sources/RswiftGenerators/PropertyListResource+Generator.swift, Sources/RswiftResources/Integrations/Bundle+Extensions.swift
Resolves https://github.com/mac-cain13/R.swift/issues/918
=> Fix support for plist items that are in arrays
